apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-build
  namespace: build
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-analysis
  namespace: build
rules:
  - apiGroups: [""]
    resources: ["namespaces", "roles", "persistentvolumeclaims", "pods", "services", "pods/log", "serviceaccounts", "pods/exec", "secrets", "configmaps"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: ["apps"]
    resources: ["deployments","statefulsets", "daemonsets"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies", "ingresses"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create","delete","get","list","patch","update","watch"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-build
  namespace: build
rules:
  - apiGroups: [""]
    resources: ["namespaces", "roles", "pods", "services", "pods/log", "serviceaccounts", "pods/exec", "secrets", "configmaps"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: ["apps"]
    resources: ["deployments","statefulsets"]
    verbs: ["create","delete","get","list","patch","update","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-build
  namespace: build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-build
subjects:
  - kind: ServiceAccount
    name: jenkins-build
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-analysis
  namespace: analysis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-analysis
subjects:
  - kind: ServiceAccount
    name: jenkins-build
    namespace: build
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-build
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create","delete","get","list","patch","update","watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["create","delete","get","list","patch","update","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-build
subjects:
  - kind: ServiceAccount
    name: jenkins-build
    namespace: build
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: jenkins-build
  apiGroup: rbac.authorization.k8s.io

##kind: StorageClass
##apiVersion: storage.k8s.io/v1
##metadata:
##  name: ebs-sc
##provisioner: ebs.csi.aws.com
##volumeBindingMode: WaitForFirstConsumer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default-reader
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - persistentvolumes
      - pods
    verbs: ["get", "watch", "list"]
  - nonResourceURLs: ["*"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [ "" ]
    resources: ["pods", "pods/exec" ]
    verbs: [ "create","delete","get","list","patch","update","watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyter-user-scheduler
rules:
  - apiGroups: [ "" ]
    resources: [ "bindings" ]
    verbs: [ "create" ]

  - apiGroups: [ "" ]
    resources: [ "endpoints" ]
    resourceNames: [ "user-scheduler-lock" ]
    verbs: [ "get", "update" ]

  - apiGroups: [ "" ]
    resources: [ "endpoints" ]
    verbs: [ "create" ]

  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create", "patch", "update" ]

  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "" ]
    resources: [ "persistentvolumeclaims" ]
    verbs: [ "get", "list", "watch", "get", "list", "patch", "update", "watch" ]

  - apiGroups: [ "" ]
    resources: [ "persistentvolumes" ]
    verbs: [ "get", "list", "watch", "get", "list", "patch", "update", "watch" ]

  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "delete", "get", "list", "watch" ]

  - apiGroups: [ "" ]
    resources: [ "pods/binding" ]
    verbs: [ "create" ]

  - apiGroups: [ "" ]
    resources: [ "pods/status" ]
    verbs: [ "patch", "update" ]

  - apiGroups: [ "" ]
    resources: [ "replicationcontrollers" ]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "apps" ]
    resources: [ "replicasets" ]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "apps" ]
    resources: [ "statefulsets" ]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    resourceNames: [ "user-scheduler-lock" ]
    verbs: [ "get", "update" ]

  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "create" ]

  - apiGroups: [ "events.k8s.io" ]
    resources: [ "events" ]
    verbs: [ "create", "patch", "update" ]

  - apiGroups: [ "extensions" ]
    resources: [ "replicasets" ]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "policy" ]
    resources: [ "poddisruptionbudgets" ]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "csinodes" ]
    verbs: [ "get", "list", "watch" ]

  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "storageclasses" ]
    verbs: [ "get", "list", "watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-reader-role-binding
subjects:
  - kind: ServiceAccount
    name: jenkins-sa
    namespace: devops
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: default-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jupyter-user-scheduler
subjects:
  - kind: ServiceAccount
    name: jenkins-build
    namespace: devops
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: jupyter-user-scheduler
  apiGroup: rbac.authorization.k8s.io
