- name: Install jenkinsci repos
  kubernetes.core.helm_repository:
    name: jenkinsci
    repo_url: "https://charts.jenkins.io"

- name: Create namespace
  kubernetes.core.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: namespace
    state: present

- name: Add Voight.org Certificates
  kubernetes.core.helm:
    name: "{{ namespace }}-certificates"
    chart_ref: ./roles/jenkins/files/certificates
    release_namespace: "{{ namespace }}"
    release_values:
      namespace: "{{ namespace }}"
      tls:
        key: "{{ voightorgkey }}"
        crt: "{{ voightorgcrt }}"

- name: Apply Jenkins Persistence
  kubernetes.core.helm:
    name: "{{ namespace }}-persistence"
    chart_ref: ./roles/jenkins/files/persistence
    release_namespace: "{{ namespace }}"

- name: Apply Jenkins Roles
  kubernetes.core.helm:
    name: "{{ namespace }}-roles"
    chart_ref: ./roles/jenkins/files/roles
    release_namespace: "{{ namespace }}"

- name: Apply Jenkins Secrets
  kubernetes.core.helm:
    name: "{{ namespace }}-secrets"
    chart_ref: ./roles/jenkins/files/secrets
    release_namespace: "{{ namespace }}"
    release_values:
      jenkins:
        namespace: "{{ namespace }}"
        user: "{{ jenkinsUser }}"
        password: "{{ jenkinsPassword }}"


- name: Apply Jenkins
  kubernetes.core.helm:
    name: "{{ deployment }}"
    chart_ref: jenkinsci/jenkins
    release_namespace: "{{ namespace }}"
    release_values:
      jenkins:
        namespace: "{{ namespace }}"
      controller:
        tagLabel: "jdk11"
        imagePullPolicy: "IfNotPresent"
        admin:
          existingSecret: jenkins
        javaOpts: "-Xms512m -Xmx512m -Dpermissive-script-security.enabled=true"
        serviceType: "{{ serviceType }}"
        loadBalancerIP: "{{ serviceLoadBalancerIP }}"
        installPlugins: "{{ installPlugins }}"
        installLatestSpecifiedPlugins: false
        additionalPlugins: "{{ additionalPlugins }}"
        initializeOnce: true
        JCasC:
          enabled: true
        podAnnotations:
          fluentbit.io/parser: jenkins
        ingress:
          enabled: true
          apiVersion: "networking.k8s.io/v1"
          hostName: "{{ ingressHostName }}"
          ingressClass: "{{ ingressClass }}"
          tls:
            - secretName: "{{ defaultTLSSecretSecret }}"
        secondaryingress:
          enabled: true
          apiVersion: "networking.k8s.io/v1"
          ingressClass: "{{ ingressClass }}"
          paths: [ /github-webhook ]
          hostName: "{{ ingressHostName }}"
          tls:
            - secretName: "{{ defaultTLSSecretSecret }}"
      agent:
        tag: "latest-jdk11"
      persistence:
        existingClaim: "jenkins-pvc"
        storageClass: ""
      rbac:
        readSecrets: true
      serviceAccount:
        name: jenkins-sa
      serviceAccountAgent:
        create: true
        name: jenkins-agent-sa
