- name: Install jenkinsci repos
  kubernetes.core.helm_repository:
    name: jenkinsci
    repo_url: "https://charts.jenkins.io"

- name: Create namespace
  kubernetes.core.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: namespace
    state: present

- name: Add Voight.org Certificates
  kubernetes.core.helm:
    name: "{{ deployment }}-certificates"
    chart_ref: ./roles/jenkins/files/certificates
    release_namespace: "{{ namespace }}"
    release_values:
      namespace: "{{ namespace }}"
      tls:
        key: "{{ voightorgkey }}"
        crt: "{{ voightorgcrt }}"

- name: Apply Jenkins Required
  kubernetes.core.helm:
    name: "{{ deployment }}-required"
    chart_ref: ../roles/jenkins/files/required
    release_namespace: "{{ namespace }}"
    release_values:
      jenkins:
        namespace: "{{ namespace }}"
        user: "{{ jenkinsUser }}"
        password: "{{ jenkinsPassword }}"

- name: Apply Jenkins
  kubernetes.core.helm:
    name: "{{ deployment }}"
    chart_ref: jenkinsci/jenkins
    release_namespace: "{{ namespace }}"
    release_values:
      jenkins:
        namespace: "{{ namespace }}"
      controller:
        tagLabel: "jdk11"
        imagePullPolicy: "IfNotPresent"
        admin:
          existingSecret: jenkins
        javaOpts: "-Xms512m -Xmx512m -Dpermissive-script-security.enabled=true"
        service:
          type: "{{ serviceType }}"
          loadBalancerIP: "{{ serviceLoadBalancerIP }}"
        installLatestSpecifiedPlugins: true
        additionalPlugins:
          #          - ace-editor:1.1
          - analysis-model-api:9.0.1
          - ansicolor:0.7.3
          - antisamy-markup-formatter:2.1
          - apache-httpcomponents-client-4-api:4.5.13-1.0
          - authentication-tokens:1.4
          - blueocean-autofavorite:1.2.4
          - blueocean-bitbucket-pipeline:1.24.0
          - blueocean-commons:1.24.0
          - blueocean-config:1.24.0
          - blueocean-core-js:1.24.0
          - blueocean-dashboard:1.24.0
          - blueocean-display-url:2.4.0
          - blueocean-events:1.24.0
          - blueocean-git-pipeline:1.24.0
          - blueocean-github-pipeline:1.24.0
          - blueocean-i18n:1.24.0
          - blueocean-jira:1.24.0
          - blueocean-jwt:1.24.0
          - blueocean-personalization:1.24.0
          - blueocean-pipeline-api-impl:1.24.0
          - blueocean-pipeline-editor:1.24.0
          - blueocean-pipeline-scm-api:1.24.0
          - blueocean-rest-impl:1.24.0
          - blueocean-rest:1.24.0
          - blueocean-web:1.24.0
          - blueocean:1.24.0
          - bootstrap4-api:4.5.2-1
          - bouncycastle-api:2.20
          - branch-api:2.6.0
          - checks-api:1.0.0
          - cloudbees-bitbucket-branch-source:2.9.2
          - cloudbees-folder:6.15
          - command-launcher:1.4
          - config-file-provider:3.7.0
          - configuration-as-code-support:1.18
          - credentials:2.5
          - data-tables-api:1.10.21-2
          - display-url-api:2.3.4
          - docker-commons:1.17
          - docker-workflow:1.24
          - durable-task:1.37
          - echarts-api:4.8.0-2
          - favorite:2.3.2
          - font-awesome-api:5.14.0-1
          - forensics-api:0.7.0
          - git-client:3.9.0
          - git-server:1.9
          - github-api:1.116
          - github-branch-source:2.9.0
          - github:1.31.0
          - h2-api:1.4.199
          - handlebars:1.1.1
          - handy-uri-templates-2-api:2.1.8-1.0
          - htmlpublisher:1.23
          - jackson2-api:2.12.3
          - jacoco:3.0.8
          - jdk-tool:1.4
          - jenkins-design-language:1.24.0
          - jira:3.1.1
          - jquery-detached:1.2.1
          - jquery3-api:3.5.1-1
          - jsch:0.1.55.2
          - junit:1.35
          - kubernetes-client-api:5.4.1
          - kubernetes-credentials-provider:0.15
          - kubernetes-credentials:0.8.0
          - lockable-resources:2.8
          - log-parser:2.1
          - mailer:1.34
          - matrix-project:1.18
          - mercurial:2.10
          - momentjs:1.1.1
          - okhttp-api:3.14.9
          - permissive-script-security:0.6
          - pipeline-build-step:2.13
          - pipeline-graph-analysis:1.10
          - pipeline-input-step:2.12
          - pipeline-maven:3.9.3
          - pipeline-milestone-step:1.3.1
          - pipeline-model-api:1.7.2
          - pipeline-model-definition:1.7.2
          - pipeline-model-extensions:1.7.2
          - pipeline-npm:0.9.2
          - pipeline-rest-api:2.15
          - pipeline-stage-step:2.5
          - pipeline-stage-tags-metadata:1.7.2
          - pipeline-stage-view:2.15
          - pipeline-utility-steps:2.6.1
          - plain-credentials:1.7
          - plugin-util-api:1.2.5
          - popper-api:1.16.0-6
          - pubsub-light:1.13
          - purge-job-history:1.4
          - resource-disposer:0.14
          - scm-api:2.6.5
          - script-security:1.78
          - snakeyaml-api:1.29.1
          - sonar:2.12
          - sse-gateway:1.23
          - ssh-credentials:1.18.1
          - ssh-steps:2.0.0
          - structs:1.23
          - token-macro:2.13
          - trilead-api:1.0.13
          - variant:1.4
          - warnings-ng:8.4.2
          - workflow-api:2.45
          - workflow-basic-steps:2.21
          - workflow-cps-global-lib:2.17
          - workflow-cps:2.92
          - workflow-durable-task-step:2.36
          - workflow-multibranch:2.22
          - workflow-scm-step:2.13
          - workflow-step-api:2.24
          - workflow-support:3.7
          - ws-cleanup:0.38
          - zap-pipeline:1.9
          - zap:1.1.0
        initializeOnce: true
        JCasC:
          enabled: true
        podAnnotations:
          fluentbit.io/parser: jenkins
        ingress:
          enabled: true
          apiVersion: "networking.k8s.io/v1"
          hostName: "{{ ingressHostName }}"
          ingressClass: "{{ ingressClass }}"
        secondaryingress:
          enabled: true
          apiVersion: "networking.k8s.io/v1"
          ingressClass: "{{ ingressClass }}"
          paths: [ /github-webhook ]
          hostName: "{{ ingressHostName }}"
          tls:
            - secretName: "{{ defaultTLSSecretSecret }}"
        agent:
          tag: "latest-jdk11"
        persistence:
          existingClaim: jenkinsnfs
        rbac:
          readSecrets: true
        serviceAccount:
          name: jenkins-sa
        serviceAccountAgent:
          create: true
          name: jenkins-agent-sa
