- name: Initialize Jenkins
  hosts: localhost
  vars_files:
    - files/jenkins-required.yaml
    - files/admin-values.yaml
  vars:
    namespace: devops

  tasks:
    - name: Install Openshift Python Library
      command: pip3 install openshift
      delegate_to: localhost

    - name: Install Ansible
      become: true
      apt:
        name: ansible
        state: present
        update_cache: yes
      delegate_to: localhost

    - name: Install Ansible Galaxy Kubernetes
      command: ansible-galaxy collection install community.kubernetes
      delegate_to: localhost

    - name: Add Jenkins CI Repo
      community.kubernetes.helm_repository:
        name: jenkinsci
        repo_url: "https://charts.jenkins.io"
      delegate_to: localhost

    - name: Create namespace
      community.kubernetes.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: namespace
        state: present
      delegate_to: localhost

    - name: Update helm repos
      command: helm repo update
      delegate_to: localhost

    - name: Copy voight.org cert
      copy:
        src: files/voight.org.crt
        dest: /tmp/
      delegate_to: localhost

    - name: Copy ca.org cert
      copy:
        src: files/ca.crt
        dest: /tmp/
      delegate_to: localhost

    - name: Copy global chart
      copy:
        src: files/global
        dest: /tmp/
      delegate_to: localhost

    - name: Add Voight.org Certificates
      command: >
        helm upgrade -i -n "{{ namespace }}" certificates /tmp/global
        --set-file tls.crt=/tmp/voight.org.crt
        --set tls.key='{{ voightorgkey }}'
        --set-file ca.crt=/tmp/ca.crt
      delegate_to: localhost

    - name: Copy Customization
      copy:
        src: ../jenkins-values.yaml
        dest: /tmp/
      delegate_to: localhost

    - name: Copy Secrets and Roles Deployment
      copy:
        src: ../jenkins-required
        dest: /tmp/
      delegate_to: localhost

    - name: Apply Jenkins Required Chart
      command: >
        helm upgrade -i -n "{{ namespace }}" jenkins-required /tmp/jenkins-required
        --set jenkins.namespace="{{ namespace }}"
        --set jenkins.gitUser='{{ gitUser }}'
        --set jenkins.gitToken='{{ gitToken }}'
        --set jenkins.gitSSHkey='{{ gitSSHkey }}'
        --set jenkins.user='{{ jenkinsUser }}'
        --set jenkins.password='{{ jenkinsPassword }}'
      delegate_to: localhost

    - name: Apply Jenkins Chart
      command: >
        helm upgrade -i -n "{{ namespace }}" jenkins jenkinsci/jenkins
        -f /tmp/jenkins-values.yaml
        --set jenkins.namespace="{{ namespace }}"
      delegate_to: localhost
