- name: Reset Jenkins
  hosts: localhost
  vars:
    namespace: devops
  tasks:
    - name: Reset Jenkins
      command: helm uninstall -n "{{ namespace }}" jenkins-required
      delegate_to: localhost

    - name: Reset Jenkins
      command: helm uninstall -n "{{ namespace }}" jenkins
      delegate_to: localhost


