---
# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: jenkins
  namespace: {{ .Values.jenkins.namespace }}
type: Opaque
data:
  jenkins-admin-user: {{ .Values.jenkins.user | b64enc }}
  jenkins-admin-password: {{ .Values.jenkins.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  # this is the jenkins id.
  name: "jenkins-key"
  labels:
    # so we know what type it is.
    "jenkins.io/credentials-type": "basicSSHUserPrivateKey"
  annotations:
    # description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "githubcredentials"
type: "kubernetes.io/ssh-auth"
stringData:
  username: git
  ssh-privatekey: |-
    {{ .Values.jenkins.gitSSHkey }}
---
apiVersion: v1
kind: Secret
metadata:
  # this is the jenkins id.
  name: "githubapi"
  labels:
    # so we know what type it is.
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    # description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "credentials for Github"
type: Opaque
stringData:
  username: {{ .Values.jenkins.gitUser }}
  password: {{ .Values.jenkins.gitToken | b64enc }}
---
