---
# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: jenkins
  namespace: {{ .Values.jenkins.namespace }}
type: Opaque
data:
  jenkins-admin-user: {{ .Values.jenkins.user | b64enc }}
  jenkins-admin-password: {{ .Values.jenkins.password | b64enc }}
